version: '3'

services:
    iobroker:
        build: ./iobroker
        container_name: iobroker-zigbee-d
        hostname: iobroker-zigbee-d
        # This port is only internal, so we can work on this while another instance of ioBroker is running on the host
        expose:
            - 8081
        volumes:
            - ..:/workspace
            - iobrokerdata-zigbee-d:/opt/iobroker
        environment:
            - LANG=en_US.UTF-8
            - LANGUAGE=en_US:en
            - LC_ALL=en_US.UTF-8
            - TZ=Europe/Berlin
            - SETGID=1000

    parcel:
        container_name: parcel-i2c
        build: ./parcel
        expose:
            - 1234
        ports:
            - '1235:1235'
        volumes:
            - ..:/workspace
        environment:
            - CHOKIDAR_USEPOLLING=1

    # Reverse proxy to load up-to-date admin sources from the repo
    nginx:
        image: nginx:latest
        depends_on:
            - iobroker
            - parcel
        links:
            - iobroker
            - parcel
        container_name: nginx-dvlp
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ..:/workspace
        ports:
            # Make the ioBroker admin available under http://localhost:8082
            - 8082:80

volumes:
    iobrokerdata-zigbee-d:
